# Generated by Django 5.1.1 on 2024-12-21 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='estado',
            field=models.CharField(choices=[('P', 'Pendiente'), ('R', 'Respondido'), ('C', 'Cerrado')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='prioridad',
            field=models.CharField(choices=[('B', 'Baja'), ('M', 'Media'), ('A', 'Alta'), ('C', 'Critica')], default='M', max_length=1),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='profile_pics/default.jpg', upload_to='profile_pics/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
