# Generated by Django 5.1.1 on 2024-12-26 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_userprofile_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('user', 'Usuario'), ('agent', 'Agente')], default='user', max_length=10),
        ),
    ]
