# Generated by Django 5.1.1 on 2024-12-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='respuesta',
            field=models.TextField(blank=True, null=True),
        ),
    ]
