# Generated by Django 5.1.5 on 2025-02-03 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_userprofile_banned_alter_userprofile_profile_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='mensaje',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='respuesta',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='banned',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('user', 'Usuario'), ('agent', 'Agente')], default='user', max_length=10),
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('respuesta', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='tickets.ticket')),
            ],
        ),
    ]
