# Generated by Django 5.1.1 on 2025-02-03 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_remove_ticket_mensaje_remove_ticket_respuesta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('user', 'Usuario'), ('agent', 'Agente')], default='active', max_length=10),
        ),
    ]
