# Generated by Django 5.1.1 on 2025-02-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_userprofile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('active', 'Activo'), ('ban', 'Baneado')], default='active', max_length=10),
        ),
    ]
